# Generated by Django 4.1.5 on 2023-01-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Appointment Title', max_length=510, verbose_name='Appointment Title'),
        ),
    ]
